### ISSUE TITLE
openstack workspace enable接口，使用subnentId时，接口报错，提示subnet不存在（No Subnet found for c75bdae0-40ed-422d-8845-71429ac318e6）

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#13]
接口命令如下：
`openstack workspace enable --domain-type LOCAL_AD --domain-name opsadm.huawei.com --domain-admin-account vdsadmin --domain-password Huawei@123 --active-domain-ip 192.168.0.85 --active-dns-ip 192.168.0.85 --vpc 615bbe8b-64c1-4c5c-b362-37a0011570a1 --subnet c75bdae0-40ed-422d-8845-71429ac318e6 --access-mode BOTH --insecure --debug
`

返回错误如下：
`https://vpc.eu-de.otc.t-systems.com:443 "GET /v2.0/subnets HTTP/1.1" 200 None
RESP: [200] Server: Web Server Date: Tue, 18 Apr 2017 07:47:10 GMT Content-Type: application/json Transfer-Encoding: chunked Connection: keep-alive Cache-Control: private, no-cache Expires: Thu, 01 Jan 1970 00:00:00 GMT Accept-Ranges: bytes Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains; 
RESP BODY: {"subnets":[{"name":"subnet-e4ea","cidr":"192.168.2.0/24","id":"543b7c1d-18f2-4e95-bc94-6eb6ae5bc4f0","enable_dhcp":true,"network_id":"fd766a5d-e36b-43fb-a35a-72f4c8e91bee","tenant_id":"c13ace79f9634257b375bba42231a4d3","dns_nameservers":["217.150.148.148","195.244.235.14"],"allocation_pools":[{"start":"192.168.2.2","end":"192.168.2.254"}],"host_routes":[],"ip_version":4,"gateway_ip":"192.168.2.1"},{"name":"subnet-e5dc","cidr":"192.168.0.0/24","id":"acc7aac7-a41a-4296-a7ff-8d9637764c90","enable_dhcp":true,"network_id":"c75bdae0-40ed-422d-8845-71429ac318e6","tenant_id":"c13ace79f9634257b375bba42231a4d3","dns_nameservers":["192.168.0.85"],"allocation_pools":[{"start":"192.168.0.2","end":"192.168.0.254"}],"host_routes":[],"ip_version":4,"gateway_ip":"192.168.0.1"},{"name":"subnet-f7f1","cidr":"192.168.1.0/24","id":"ea681e72-c95d-48cf-a059-b988b50545c8","enable_dhcp":true,"network_id":"9502d5b2-3058-4562-985a-18dbbc9d9baa","tenant_id":"c13ace79f9634257b375bba42231a4d3","dns_nameservers":["217.150.148.148","195.244.235.14"],"allocation_pools":[{"start":"192.168.1.2","end":"192.168.1.254"}],"host_routes":[],"ip_version":4,"gateway_ip":"192.168.1.1"}]}

ResourceNotFound: No Subnet found for c75bdae0-40ed-422d-8845-71429ac318e6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/workspaceclient/osc/v1/workspace.py", line 50, in take_action
    for subnet in args.subnets
  File "/usr/local/lib/python2.7/dist-packages/openstack/network/v2/_proxy.py", line 1696, in find_subnet
    ignore_missing=ignore_missing)
  File "/usr/local/lib/python2.7/dist-packages/openstack/proxy.py", line 92, in _find
    ignore_missing=ignore_missing)
  File "/usr/local/lib/python2.7/dist-packages/openstack/resource.py", line 968, in find
    "No %s found for %s" % (cls.__name__, name_or_id))
ResourceNotFound: ResourceNotFound: No Subnet found for c75bdae0-40ed-422d-8845-71429ac318e6
clean_up EnableWorkspace: ResourceNotFound: No Subnet found for c75bdae0-40ed-422d-8845-71429ac318e6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openstackclient/shell.py", line 119, in run
    ret_val = super(OpenStackShell, self).run(argv)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "/usr/local/lib/python2.7/dist-packages/openstackclient/shell.py", line 164, in run_subcommand
    ret_value = super(OpenStackShell, self).run_subcommand(argv)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/workspaceclient/osc/v1/workspace.py", line 50, in take_action
    for subnet in args.subnets
  File "/usr/local/lib/python2.7/dist-packages/openstack/network/v2/_proxy.py", line 1696, in find_subnet
    ignore_missing=ignore_missing)
  File "/usr/local/lib/python2.7/dist-packages/openstack/proxy.py", line 92, in _find
    ignore_missing=ignore_missing)
  File "/usr/local/lib/python2.7/dist-packages/openstack/resource.py", line 968, in find
    "No %s found for %s" % (cls.__name__, name_or_id))
ResourceNotFound: ResourceNotFound: No Subnet found for c75bdae0-40ed-422d-8845-71429ac318e6

END return value: 1
`

**Comment by IamFive** [comment]
我记得 这边原来讨论过。传的不是 subnet-id好像。

**Comment by IamFive** [comment]
![image](https://cloud.githubusercontent.com/assets/1578702/25123329/987fb9bc-245a-11e7-958d-0c415fe2ba81.png)

**Comment by jiang-jiajia** [comment]
@IamFive 
我传入的就是network  id，但是报错了。

`root@11111111:/home/ubuntu# openstack subnet list --insecure
+--------------------------------------+-------------+--------------------------------------+----------------+
| ID                                   | Name        | Network                              | Subnet         |
+--------------------------------------+-------------+--------------------------------------+----------------+
| 543b7c1d-18f2-4e95-bc94-6eb6ae5bc4f0 | subnet-e4ea | fd766a5d-e36b-43fb-a35a-72f4c8e91bee | 192.168.2.0/24 |
| acc7aac7-a41a-4296-a7ff-8d9637764c90 | subnet-e5dc | c75bdae0-40ed-422d-8845-71429ac318e6 | 192.168.0.0/24 |
| ea681e72-c95d-48cf-a059-b988b50545c8 | subnet-f7f1 | 9502d5b2-3058-4562-985a-18dbbc9d9baa | 192.168.1.0/24 |
+--------------------------------------+-------------+--------------------------------------+----------------+
`

`root@11111111:/home/ubuntu# openstack network list --insecure
+--------------------------------------+--------------------------------------+--------------------------------------+
| ID                                   | Name                                 | Subnets                              |
+--------------------------------------+--------------------------------------+--------------------------------------+
| 9502d5b2-3058-4562-985a-18dbbc9d9baa | 615bbe8b-64c1-4c5c-b362-37a0011570a1 | ea681e72-c95d-48cf-a059-b988b50545c8 |
| c75bdae0-40ed-422d-8845-71429ac318e6 | 615bbe8b-64c1-4c5c-b362-37a0011570a1 | acc7aac7-a41a-4296-a7ff-8d9637764c90 |
| fd766a5d-e36b-43fb-a35a-72f4c8e91bee | 615bbe8b-64c1-4c5c-b362-37a0011570a1 | 543b7c1d-18f2-4e95-bc94-6eb6ae5bc4f0 |
| 0a2228f2-7f8a-45f1-8e09-9039e1d09975 | admin_external_net                   |                                      |
+--------------------------------------+--------------------------------------+--------------------------------------+
`

**Comment by IamFive** [comment]
你传的哪里是 subnet-id。。

**Comment by jiang-jiajia** [comment]
@IamFive 
可能我说得有点问题，这个在openstack里面是network id，但是在我们华为公有云里面，console上面呈现的，其实是subnet id，所以我这里所说的是subnet id是我们console上面呈现的subnet id，不是openstack里面的subnet id。

**Comment by IamFive** [comment]
你们console怎么呈现跟这边没有关系。。 这个问题老早就就讨论过了。

**Comment by jiang-jiajia** [comment]
@IamFive 
下面这个是以前你在 [https://github.com/Huawei/OpenStackClient_Workspace/issues/3] 中修改的方式。
我现在就是用的查询到的network-id来作为输入，但是你报错了。


```
pull master 代码，已经更新成如下获取方式：

vpc_id 会使用 openstack router list 对应的库 去查找（支持 router name id），并使用查找到的对象的ID作为输入
subnet 会使用 openstack subnet list 对应的库 去查找（支持 subnet name id），并使用查找到的对象的 network_id 作为输入
但是还是感觉怪怪的，如果要存 subnet，为什么不直接用 subnet-id 而要用 network-id。用户用的时候也会不统一，输入的时候用subnet-name 作为输入，显示的时候却是 network-id
```


```
root@11111111:/home/ubuntu# openstack network list --insecure -c ID
+--------------------------------------+
| ID                                   |
+--------------------------------------+
| c75bdae0-40ed-422d-8845-71429ac318e6 |
+--------------------------------------+
```

**Comment by IamFive** [comment]
并不是用什么的问题，你们PM决定了用这个

**Comment by IamFive** [comment]
>下面这个是以前你在 [https://github.com/Huawei/OpenStackClient_Workspace/issues/3] 中修改的方式。
我现在就是用的查询到的network-id来作为输入，但是你报错了。

> subnet 会使用 *openstack subnet list* 对应的库 去查找（支持 subnet name id），并使用查找到的对象的 network_id 作为输入

真的，看认真点。。

**Comment by jiang-jiajia** [comment]
@IamFive 
懂了....
这个概念有点绕，又把我绕进去了
