### ISSUE TITLE
openstack workspace enable的--domain-password密码规则有问题

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#2]
![image](https://cloud.githubusercontent.com/assets/25836064/23057448/2f2be2f0-f52b-11e6-929e-8cace2ce679c.png)

**Comment by IamFive** [comment]
这个不是密码规则有问题。

openstack 命令是以 shell 的形式运行的，所以命令要遵循shell的规则。你输入的 !@# 触发了 shell 的命令。
如果真要输入 !@# 可以把输入用 **单引号** 包起来。 --domain-password='wks123!@#'

**Comment by jiang-jiajia** [comment]
赞！
用单引号包起来后确实可以执行了。
