### ISSUE TITLE
openstack workspace enable使用vpcID和subnetID，接口返回失败

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#4]
[enableWorkspace.txt](https://github.com/Huawei/OpenStackClient_Workspace/files/782672/enableWorkspace.txt)

**Comment by IamFive** [comment]
duplicated with issue #3

**Comment by jiang-jiajia** [comment]
![image](https://cloud.githubusercontent.com/assets/25836064/23110606/99b4e764-f75d-11e6-9a07-1692be31ea06.png)

我通过console开通的服务，再通过命令查询，显示的vpcID和subnetID是我最初通过命令开通服务时的参数。
