### ISSUE TITLE
openstack workspace policy edit编辑策略时，策略需要体现前后依赖关系

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#5]
当前的策略的配置是扁平化的，看不出来依赖关系，但是，实际上策略的配置是有依赖关系的。
例如：如果没有开启usb-port-redirection这个总开关，则无论配置是否开启/禁用usb-image、usb-video、usb-printer、usb-storage、usb-smart-card都没有意义，原因是总开关是关闭的。

root@ubuntu:/# openstack workspace policy edit -h
usage: openstack workspace policy edit [-h]
                                       [--enable-usb-port-redirection | --disable-usb-port-redirection]
                                       [--enable-usb-image | --disable-usb-image]
                                       [--enable-usb-video | --disable-usb-video]
                                       [--enable-usb-printer | --disable-usb-printer]
                                       [--enable-usb-storage | --disable-usb-storage]
                                       [--enable-usb-smart-card | --disable-usb-smart-card]
                                       [--enable-printer-redirection | --disable-printer-redirection]
                                       [--enable-sync-client-default-printer | --disable-sync-client-default-printer]
                                       [--universal-printer-driver {Default,HDP XPSDrv Driver,Universal Printing PCL 5,Universal Printing PCL 6,Universal Printing PS}]
                                       [--file-redirection-mode {DISABLED,READ_ONLY,READ_AND_WRITE}]
                                       [--enable-fixed-drive | --disable-fixed-drive]
                                       [--enable-removable-drive | --disable-removable-drive]
                                       [--enable-cd-rom-drive | --disable-cd-rom-drive]
                                       [--enable-network-drive | --disable-network-drive]
                                       [--clipboard-redirection {DISABLED,SERVER_TO_CLIENT_ENABLED,CLIENT_TO_SERVER_ENABLED,TWO_WAY_ENABLED}]
                                       [--enable-hdp-plus | --disable-hdp-plus]
                                       [--display-level {SMOOTHNESS_FIRST,QUALITY_FIRST}]
                                       [--bandwidth <Kbps>]
                                       [--frame-rate <FPS>]
                                       [--video-frame-rate <FPS>]
                                       [--smoothing-factor <smoothing-factor>]
                                       [--lossy-compression-quality <quality>]

当前console上面的配置方式如下图所示：
![image](https://cloud.githubusercontent.com/assets/25836064/23115629/117be194-f781-11e6-9f7f-68546c74651a.png)

**Comment by IamFive** [comment]
理解你的意思，我做的时候也在考虑这个问题。
但是 python argparse 库没有提供这种依赖关系的 参数输入的功能。目前来看是实现不了。

**Comment by IamFive** [comment]
PM 没有回复，这个issue就不修改了。如果有好的方案，可以comment下，我再做调整
