### ISSUE TITLE
openstack desktop create命令，部分参数为必选参数，烦请进行修改

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#6]
user_name、user_email、product_id、root_volume、computer_name为必选参数。

root@ubuntu:/# openstack desktop create -h
usage: openstack desktop create [-h] --user-name <user-name> --user-email
                                <email> --computer-name <computer-name>
                                --product-id <product-id>
                                [--image-id <image-id>] --root-volume
                                <volume-type:volume-size>
                                [--data-volume <volume-type:volume-size>]
                                [--security-group <security-group>]
                                [--nic <subnet=subnet-uuid,ip=ip-address>]

Create a new desktop

optional arguments:
  -h, --help            show this help message and exit
  --user-name <user-name>
                        Desktop Login UserName (character [a-zA-Z0-9-_]
                        allowed, start with alphabet, length between 1-20)
  --user-email <email>  User Mail to receive notification when desktop created
  --computer-name <computer-name>
                        Desktop Computer name (must be unique, character
                        [a-zA-Z0-9-_] allowed, start with alphabet, length
                        between 1-15)
  --product-id <product-id>
                        desktop product id
  --image-id <image-id>
                        desktop customer image id
  --root-volume <volume-type:volume-size>
                        Desktop Root Volume, volume type [SSD|SATA], volume
                        size unit is GB (example: SSD:80)
  --data-volume <volume-type:volume-size>
                        Desktop data Volume, volume type [SSD|SATA], volume
                        size unit is GB (example: SSD:80). (Repeat option to
                        set multiple data volumes.)
  --security-group <security-group>
                        Security group to assign to this desktop (name or ID)
                        (repeat option to set multiple security groups)
  --nic <subnet=subnet-uuid,ip=ip-address>
                        NIC to assign to this desktop. subnet is required, ip
                        is optional. (Repeat option to set multiple NIC)

**Comment by IamFive** [comment]
现在已经是必填项。usage 里面 假如是非必填的，会用 [] 括起来。

```
root@iZ230lrzis5Z:/data/www/python-vbclient# openstack desktop create 
usage: openstack desktop create [-h] --user-name <user-name> --user-email
                                <email> --computer-name <computer-name>
                                --product-id <product-id>
                                [--image-id <image-id>] --root-volume
                                <volume-type:volume-size>
                                [--data-volume <volume-type:volume-size>]
                                [--security-group <security-group>]
                                [--nic <subnet=subnet-uuid,ip=ip-address>]
```

假如不输入参数：

```
root@iZ230lrzis5Z:/data/www/python-vbclient# openstack desktop create 
usage: openstack desktop create [-h] --user-name <user-name> --user-email
                                <email> --computer-name <computer-name>
                                --product-id <product-id>
                                [--image-id <image-id>] --root-volume
                                <volume-type:volume-size>
                                [--data-volume <volume-type:volume-size>]
                                [--security-group <security-group>]
                                [--nic <subnet=subnet-uuid,ip=ip-address>]
openstack desktop create: error: argument --user-name is required
```
