### ISSUE TITLE
openstack desktop detail list应用于查询桌面详细信息，查询结果字段少于Workspace API提供的返回字段

### ISSUE THREAD

**Issue by jiang-jiajia** [Huawei/OpenStackClient_Workspace#8]
命令如下：包含可选参数：status、desktop-ip、user-name、computer-name：
usage: openstack desktop detail list [-h] [-f {csv,json,table,value,yaml}]
                                     [-c COLUMN] [--max-width <integer>]
                                     [--print-empty] [--noindent]
                                     [--quote {all,minimal,none,nonnumeric}]
                                     [--status {ACTIVE,SHUTOFF,ERROR}]
                                     [--desktop-ip <desktop-ip>]
                                     [--user-name <user-name>]
                                     [--computer-name <computer-name>]
                                     [--marker <desktop-id>] [--limit <count>]

返回结果如下：包括返回字段：Desktop Id、Computer Name、User Name、Product Id、Login Status、Status：
![image](https://cloud.githubusercontent.com/assets/25836064/23122117/dfcab2c0-f79d-11e6-9a91-3976591a9932.png)

Workspace的API文档中，描述的返回结果中，包括的字段：desktop_id、computer_name、status、created、addresses、flavor、security_groups、metadata、user_name、login_status、product_id、root_volume、data_volumes、vpcid等多个字段

我这边提单时截图总是有问题，时不时贴图失败，烦请从Workspace API文档中获取相关返回字段信息的详细描述。

**Comment by IamFive** [comment]
这个就是这么设计的，因为在console界面下，在展示列表的时候，可选的列是有限的。太多列会导致用户看的时候会非常困难，同时有些列并不是那么要紧，可以不显示（跟浏览器的时候一样，也是会选择性的输出一些关键列）。

如果觉得输出里面选择的列有问题，有更重要的列需要展示，可以建 issue给我，同时列出要改成哪些列。

**Comment by IamFive** [comment]
ssh 工具可以使用 Xshell，在选项里把鼠标右键改成 选中拷贝，就很容易复制拷贝了。:)
